# Generated by Django 3.1 on 2023-09-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='courses',
            field=models.ManyToManyField(to='degree_checklist.Course'),
        ),
    ]
