# Generated by Django 3.1 on 2023-09-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0002_degree_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('studentID', models.CharField(max_length=15)),
                ('coursestaken', models.ManyToManyField(to='degree_checklist.Course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.department')),
            ],
        ),
    ]
