# Generated by Django 3.1 on 2023-09-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='courses',
        ),
        migrations.CreateModel(
            name='Degreecheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='degree_checklist.Course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
    ]
